spring.application.name=SpringBootRestApi_JPA
server.port=7868
#actuator

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=health,info,beans,env,hello,metrics
management.endpoint.health.show-details=always

# Database Connfiguration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/student_db
spring.datasource.username=root
spring.datasource.password=root@39
 
# hibernate / JPA COnfiguration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
 
# hikari
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=5
 
# Logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.=info
#debug=true
#trace=true
 
#spring.output.ansi.enabled=always
logging.file.path=logs/
logging.file.name=logs/application.log